name: crossplat_objectid
description: Cross-platform BSON ObjectId implementation in Dart
version: 2.1.0
authors:
  - Kwang Yul Seo <kwangyul.seo@gmail.com>
  - Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/kseo/bson_objectid

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test:
